#pragma kernel CSGrassGen

#include "./Math.hlsl"
#include "Common.hlsl"

#define LOD_MIN_DISTANCE 10.0
#define LOD_MAX_DISTANCE 100.0
#define LOD_LEVELS 4.0
#define LOD_MAX 4
#define LOD_MIN 0

RWStructuredBuffer<GrassParams> _GrassParams;
AppendStructuredBuffer<TriangleData> _Triangles;
RWStructuredBuffer<LineData> _LinesRW;
RWStructuredBuffer<IndirectArgs> _IndirectArgsBuffer;

int _ElementCount;
float3 _WorldSpaceCameraPos;

int __lodLevel(float3 positionWS) {
    float dist = distance(positionWS, _WorldSpaceCameraPos);
    float f = 1.0 - clamp((dist - LOD_MIN_DISTANCE) / (LOD_MAX_DISTANCE - LOD_MIN_DISTANCE), 0.01, 1.00);
    f = (f*f)*(f*f);
    int lod = int(LOD_LEVELS * f);
    return lod;
}

[numthreads(128,1,1)]
void CSGrassGen(uint3 uid : SV_DispatchThreadID)
{
    // int index = uid.x * 128  + uid.y + uid.z;
    // if(index > _ElementCount)
    // {
    //     return;
    // }

    // TriangleData tri;
    // VertexData vert;
    // VertexData vert0;
    // VertexData vert1;
    
    // // 每次处理两个点
    // LineData lines = _LinesRW[index];
    // vert0 = lines.vertices[0];
    // vert1 = lines.vertices[1];

    // float3 rnd = rand3(vert0.positionWS + index) * 2 - 1;
    // float2 cs = float2(sin(rnd.z * PI), cos(rnd.z * PI));
    // float3 right = float3(cs.x, 0, cs.y);

    // float curvation = 0;
    // float3x3 rot0 = _AngleAxis3x3(vert0.weight * curvation, right);
    // float3x3 rot1 = _AngleAxis3x3(vert1.weight * curvation, right);

    // int lod = __lodLevel(vert0.positionWS); 
    // int _NUM_SEGS = max(lod - 1, 0);

    // float3 baseOffset = right * _GrassParams[0]._WIDTH;
    // float3 deltaOffset = baseOffset / (float)(_NUM_SEGS + 2);
    
    // if(vert1.weight==1.0)
    // {
    //     InterlockedAdd(_IndirectArgsBuffer[0].numVerticesPerInstance, 3);

    //     float3 v0 = vert0.positionWS + baseOffset;
    //     float3 v1 = vert0.positionWS - baseOffset; 
    //     float3 v2 = vert1.positionWS;
    //     vert.normalWS = vert1.normalWS; vert.weight = vert0.weight; vert.positionWS = v1; tri.vertices[0] = vert;
    //     vert.normalWS = vert1.normalWS; vert.weight = vert0.weight; vert.positionWS = v2; tri.vertices[2] = vert;
    //     vert.normalWS = vert1.normalWS; vert.weight = vert1.weight; vert.positionWS = v2; tri.vertices[1] = vert;
    //     _Triangles.Append(tri);
    // }
    // else
    // {
    //     InterlockedAdd(_IndirectArgsBuffer[0].numVerticesPerInstance, 6);

    //     float3 v0 = vert0.positionWS + baseOffset;
    //     float3 v1 = vert0.positionWS - baseOffset; 
    //     float3 v2 = vert1.positionWS - deltaOffset;
    //     float3 v3 = vert1.positionWS + deltaOffset;

    //     vert.normalWS = vert0.normalWS; vert.weight = vert0.normalWS; vert.positionWS = v0; tri.vertices[0] = vert;
    //     vert.normalWS = vert0.normalWS; vert.weight = vert0.normalWS; vert.positionWS = v1; tri.vertices[2] = vert;
    //     vert.normalWS = vert1.normalWS; vert.weight = vert1.normalWS; vert.positionWS = v2; tri.vertices[1] = vert; 
    //     _Triangles.Append(tri);

    //     vert.normalWS = vert0.normalWS; vert.weight = vert0.normalWS; vert.positionWS = v1; tri.vertices[0] = vert;
    //     vert.normalWS = vert1.normalWS; vert.weight = vert1.normalWS; vert.positionWS = v2; tri.vertices[1] = vert;
    //     vert.normalWS = vert1.normalWS; vert.weight = vert1.normalWS; vert.positionWS = v3; tri.vertices[2] = vert;
    //     _Triangles.Append(tri);
    // }
}
